name: Purge jsDelivr Cache

on:
  push:
    paths:
      - 'offerings.js'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for GitHub to propagate
        run: sleep 600 # Increased to 10 minutes to be safe
      - name: Purge jsDelivr
        run: |
          # Purge the main file
          curl -i https://purge.jsdelivr.net/gh/gwgeorgian/ctl_offerings@main/offerings.js
          # Purge the versionless file
          curl -i https://purge.jsdelivr.net/gh/gwgeorgian/ctl_offerings/offerings.js
